- type: loadoutGroup
  id: SynthEquipmentAU14
  name: au14-loadout-group-synth-equipment
  minLimit: 0
  maxLimit: 2
  loadouts:
  - SynthBreachingHammerAU14
  - MaintenanceJackAU14
  - PortableDialysisAU14
  - AU14SprayCleanerExperimentalAU14
  - AU14CMScalpelManager
  - AU14telebatonloadout
  - AU14CompactNailgunKit
  - CMUDefibrillatorCompactSynthLoadout
  - RMCWelderExperimentalLoadout
