using Content.Shared.CMU14.Fighter;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.Fighter;

[GenerateTypedNameReferences]
public sealed partial class FighterAirspaceRadarControl : PanelContainer
{
    public FighterAirspaceRadarControl()
    {
        RobustXamlLoader.Load(this);
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#0B1410F5"),
            BorderColor = Color.FromHex("#5C6854"),
            BorderThickness = new Thickness(1),
        };
    }

    public void SetState(FighterAirspaceRadarEvent state, byte[] terrain)
    {
        Map.SetState(state, terrain);
        Title.Text = Loc.GetString(state.Organic ? "cmu-boiler-air-title" : "cmu-manpad-radar-title");
        Identification.Text = Loc.GetString(state.Organic ? "cmu-boiler-air-cost"
            : state.IgnoreIFF ? "cmu-manpad-radar-no-iff" : "cmu-manpad-radar-iff");
        Identification.Warning = state.IgnoreIFF && !state.Organic;
        var sector = FighterAirCombat.SectorAt(state.Battlefield, state.OperatorPosition);
        Sector.Text = Loc.GetString(sector < 0 ? "cmu-manpad-radar-outside" : "cmu-manpad-radar-sector",
            ("sector", sector < 0 ? "—" : FighterAirCombat.Label(state.Battlefield, sector)), ("count", state.Contacts.Count));
        Status.Text = Loc.GetString(!state.Loaded ? state.Organic ? "cmu-boiler-air-empty" : "cmu-manpad-radar-empty"
            : state.CooldownSeconds > 0 ? state.Organic ? "cmu-boiler-air-cycling" : "cmu-manpad-radar-cycling"
            : !state.Aiming ? "cmu-manpad-radar-lowered"
            : state.LockSeconds > 0 ? "cmu-manpad-radar-lock" : "cmu-manpad-radar-scanning",
            ("seconds", Math.Max(state.CooldownSeconds, state.LockSeconds).ToString("0.0")));
        Status.Warning = !state.Loaded || state.LockSeconds > 0;
    }
}
