using System.Numerics;
using System.Linq;
using Content.Client.Viewport;
using Content.Shared.CMU14.Fighter;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.Fighter;

[GenerateTypedNameReferences]
public sealed partial class FighterCockpitControl : LayoutContainer
{
    private readonly FighterCloudControl _clouds;
    private readonly FighterCloudControl _exteriorClouds;
    private readonly FighterRouteControl _chart;
    private readonly FighterSightControl _sight;
    private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    private float _receivedHeight = -1;
    private float _receivedSpeed = -1;
    private float _selectedHeight = 350;
    private float _selectedSpeed = 12;
    private FighterAircraftComponent? _aircraft;
    private readonly Action<float, float> _settings;
    private bool? _pilotRole;
    private TimeSpan _nextReadouts;
    private bool _grounded;
    private bool _airspace;
    private bool _targeting;
    private readonly List<FighterCockpitButton> _weapons = [];
    private readonly Dictionary<NetEntity, FighterCockpitButton> _targets = [];
    private readonly Action<NetEntity> _selectTarget;
    private readonly bool _spectating;

    public ScalingViewport SensorViewport => Ground;
    public bool CameraControl => _airspace && _targeting;

    public FighterCockpitControl(Action<FighterCommand> send, Action<Vector2, Vector2> plan, Action<float, float> settings,
        Action<int> selectWeapon, Action<NetEntity> selectTarget, Action<int> selectSector, bool spectating = false,
        Action? stopObserving = null)
    {
        RobustXamlLoader.Load(this);
        _spectating = spectating;
        StopObserving.Visible = spectating && stopObserving != null;
        StopObserving.OnPressed += _ => stopObserving?.Invoke();
        _settings = settings;
        _selectTarget = selectTarget;
        Ground.ViewportSize = Exterior.ViewportSize = new Vector2i(960, 540);
        Ground.MinimumRenderInterval = Exterior.MinimumRenderInterval = TimeSpan.FromMilliseconds(33);
        _clouds = new FighterCloudControl(Ground);
        _exteriorClouds = new FighterCloudControl(Exterior) { Canopy = true };
        Scene.AddChild(_clouds);
        _sight = new FighterSightControl(Ground);
        Scene.AddChild(_sight);
        ExteriorScene.AddChild(_exteriorClouds);
        _chart = new FighterRouteControl { ReadOnly = spectating };
        ChartHost.AddChild(_chart);
        SetAnchorAndMarginPreset(_chart, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(_clouds, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(_sight, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(_exteriorClouds, LayoutPreset.Wide);
        ViewPanel.PanelOverride = ConsolePanel();
        LoadoutPanel.PanelOverride = ConsolePanel();
        ControlsPanel.PanelOverride = ConsolePanel();
        AltitudeSwitch.PanelOverride = ConsolePanel();
        SpeedSwitch.PanelOverride = ConsolePanel();
        EjectPanel.PanelOverride = ConsolePanel();
        IncomingPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#28130FF5"),
            BorderColor = Color.FromHex("#F09A59"),
            BorderThickness = new Thickness(2),
        };
        _chart.SelectSector = selectSector;
        _chart.SelectTarget = id => { selectTarget(id); ShowOptics(true); };
        FlightTab.OnPressed += _ => ShowRoute(true);
        FlightTab.ToolTip = Loc.GetString("cmu-fighter-pilot-help");
        TargetingTab.OnPressed += _ => ShowOptics(true);
        TargetingTab.ToolTip = Loc.GetString("cmu-fighter-shared-sight");
        AirCover.OnPressed += _ => ShowRoute(true, !_chart.CoverageMode);
        AirCover.ToolTip = Loc.GetString("cmu-fighter-cover-help");
        Flares.OnPressed += _ => send(FighterCommand.Flares);
        IncomingFlares.OnPressed += _ => send(FighterCommand.Flares);
        for (var i = 0; i <= FighterWeaponsComponent.GauSlot; i++)
        {
            var slot = i;
            var button = i == FighterWeaponsComponent.GauSlot ? Gau : new FighterCockpitButton();
            if (i != FighterWeaponsComponent.GauSlot)
            {
                WeaponSlots.AddChild(button);
                SetAnchorLeft(button, i % 3 / 3f);
                SetAnchorRight(button, (i % 3 + 1) / 3f - .02f);
                SetAnchorTop(button, i / 3 * .52f);
                SetAnchorBottom(button, i / 3 * .52f + .48f);
            }
            button.OnPressed += _ => selectWeapon(slot);
            _weapons.Add(button);
        }
        Fire.OnPressed += _ => send(FighterCommand.Fire);
        PrepareRun.OnPressed += _ => { send(FighterCommand.PrepareRun); ShowRoute(true); };
        PrepareRun.ToolTip = Loc.GetString("cmu-fighter-prepare-help");
        QueueFire.OnPressed += _ => send(FighterCommand.QueueFire);
        QueueFire.ToolTip = Loc.GetString("cmu-fighter-queue-help");
        CameraLock.OnPressed += _ => send(FighterCommand.Lock);
        CameraLock.ToolTip = Loc.GetString("cmu-fighter-lock-help");
        CameraZoom.OnPressed += _ => send(FighterCommand.Zoom);
        CameraZoom.ToolTip = Loc.GetString("cmu-fighter-zoom");
        Laser.OnPressed += _ => { ShowOptics(true); send(FighterCommand.Laser); };
        Laser.ToolTip = Loc.GetString("cmu-fighter-laser-help");
        Mark.OnPressed += _ => send(FighterCommand.Mark);
        Mark.ToolTip = Loc.GetString("cmu-fighter-mark");
        Entry.OnPressed += _ => _chart.EditEntry = true;
        Exit.OnPressed += _ => _chart.EditEntry = false;
        Apply.OnPressed += _ => plan(_chart.Entry, _chart.Exit);
        Launch.OnPressed += _ => send(FighterCommand.Launch);
        Return.OnPressed += _ => send(_grounded ? FighterCommand.Takeoff : FighterCommand.Return);
        NormalVision.OnPressed += _ => send(FighterCommand.VisionNormal);
        NightVision.OnPressed += _ => send(FighterCommand.VisionNight);
        ThermalVision.OnPressed += _ => send(FighterCommand.VisionThermal);
        Swap.OnPressed += _ => send(FighterCommand.SwapSeat);
        Leave.OnPressed += _ => send(FighterCommand.LeaveSeat);
        ConfirmEject.OnPressed += _ => send(FighterCommand.ConfirmEject);
        CancelEject.OnPressed += _ => send(FighterCommand.CancelEject);
        LowAltitude.OnPressed += _ => SelectAltitude(350);
        MediumAltitude.OnPressed += _ => SelectAltitude((FighterFlight.CloudBase + FighterFlight.CloudTop) / 2);
        HighAltitude.OnPressed += _ => SelectAltitude(FighterFlight.MaximumHeight);
        NearStall.OnPressed += _ => SelectSpeed(_aircraft?.MinimumSpeed ?? 8);
        Cruise.OnPressed += _ => SelectSpeed(12);
        Afterburner.OnPressed += _ => SelectSpeed(_aircraft?.MaximumSpeed ?? 26);
        LowAltitude.ToolTip = Loc.GetString("cmu-fighter-height", ("height", 350));
        MediumAltitude.ToolTip = Loc.GetString("cmu-fighter-height", ("height", (FighterFlight.CloudBase + FighterFlight.CloudTop) / 2));
        HighAltitude.ToolTip = Loc.GetString("cmu-fighter-height", ("height", FighterFlight.MaximumHeight));
        SensorStatus.ToolTip = Loc.GetString("cmu-fighter-range-help");
        NightVision.ToolTip = Loc.GetString("cmu-fighter-night-help");
        ThermalVision.ToolTip = Loc.GetString("cmu-fighter-thermal-help");
        RefreshPanels();
    }

    private static StyleBoxFlat ConsolePanel() => new()
    {
        BackgroundColor = Color.FromHex("#0B1410"),
        BorderColor = Color.FromHex("#5C6854"),
        BorderThickness = new Thickness(1),
    };

    private void RefreshPanels()
    {
        RoutePanel.Visible = !_targeting;
        TargetingControls.Visible = CameraControl;
        FlightTab.Lit = !_targeting;
        TargetingTab.Lit = _targeting;
        TargetingTab.Disabled = !_airspace;
        TargetingTab.ToolTip = Loc.GetString(_airspace ? "cmu-fighter-shared-sight" : "cmu-fighter-targeting-ground");
        Scene.Visible = CameraControl;
        ExteriorScene.Visible = _airspace;
        RouteEditing.Visible = !_spectating && !_chart.CoverageMode && _pilotRole == true;
        Launch.Visible = !_spectating && !_chart.CoverageMode && _pilotRole == true;
        CoverageHelp.Visible = !_spectating && _chart.CoverageMode;
        RouteTitle.Text = Loc.GetString(_chart.CoverageMode ? "cmu-fighter-cover-title" : "cmu-fighter-airspace");
        InvalidateMeasure();
    }

    public void ShowRoute(bool visible, bool coverage = false)
    {
        // The chart now lives in a persistent left-hand display, not a popup.
        if (visible) _targeting = false;
        _chart.CoverageMode = visible && coverage && _airspace;
        RefreshPanels();
    }

    public void ShowOptics(bool visible)
    {
        _targeting = visible && _airspace;
        RefreshPanels();
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        // Keep both work areas docked and leave the aircraft unobstructed between them.
        const float margin = 12;
        var rightWidth = Math.Min(340, finalSize.X * .31f);
        var leftWidth = Math.Min(520, finalSize.X * .38f);
        var rightStart = finalSize.X - rightWidth - margin;
        SetMarginLeft(ControlsPanel, rightStart);
        SetMarginRight(ControlsPanel, finalSize.X - margin);
        SetMarginTop(ControlsPanel, margin);
        var controlsHeight = Math.Min(ControlsContent.DesiredSize.Y + 2, Math.Max(1, finalSize.Y - margin * 2));
        SetMarginBottom(ControlsPanel, margin + controlsHeight);
        SetMarginLeft(LeftColumn, margin);
        SetMarginRight(LeftColumn, margin + leftWidth);
        SetMarginTop(LeftColumn, margin);
        SetMarginBottom(LeftColumn, finalSize.Y - margin);

        var middleWidth = Math.Max(1, rightStart - leftWidth - margin * 3);
        var height = Math.Min(finalSize.Y * .55f, middleWidth * 335 / 266);
        var width = height * 266 / 335;
        var center = (leftWidth + margin + rightStart) / 2;
        SetMarginLeft(Ship, center - width / 2);
        SetMarginRight(Ship, center + width / 2);
        SetMarginTop(Ship, finalSize.Y - margin - height);
        SetMarginBottom(Ship, finalSize.Y - margin);
        return base.ArrangeOverride(finalSize);
    }

    private static void FillViewport(ScalingViewport viewport)
    {
        var dimension = viewport.PixelSize.X * 540 >= viewport.PixelSize.Y * 960
            ? ScalingViewportIgnoreDimension.Vertical
            : ScalingViewportIgnoreDimension.Horizontal;
        if (viewport.IgnoreDimension != dimension) viewport.IgnoreDimension = dimension;
        var renderScale = Math.Clamp((int) Math.Ceiling(Math.Max(viewport.PixelSize.X / 960f,
            viewport.PixelSize.Y / 540f)), 1, 2);
        if (viewport.FixedRenderScale != renderScale) viewport.FixedRenderScale = renderScale;
    }

    public void UpdateFlight(FighterAircraftComponent aircraft, FighterChartComponent? chart, FighterSeatComponent seat,
        IEye eye, IEye exteriorEye, Angle exteriorHeading, FighterSeatComponent? observer, EntityUid? pilotCrew, EntityUid? observerCrew,
        FighterWeaponsComponent? weapons, FighterAirCombatComponent? combat, FighterEffectsComponent? effects)
    {
        _aircraft = aircraft;
        var groundScene = FighterFlight.GroundScene(aircraft);
        var inAirspace = !groundScene;
        _grounded = aircraft.GroundState == FighterGroundState.Grounded;
        if (_pilotRole != seat.Pilot || _airspace != inAirspace)
        {
            _pilotRole = seat.Pilot;
            _airspace = inAirspace;
            _nextReadouts = TimeSpan.Zero;
            RoleTitle.Text = Loc.GetString(_spectating
                ? seat.Pilot ? "cmu-fighter-spectating-pilot" : "cmu-fighter-spectating-wso"
                : seat.Pilot ? "cmu-fighter-pilot-controls" : "cmu-fighter-observer-controls");
            _chart.CoverageMode = false;
            ShowOptics((_spectating || !seat.Pilot) && _airspace);
        }
        FillViewport(Ground);
        FillViewport(Exterior);
        Ground.Eye = eye;
        Exterior.Eye = exteriorEye;
        var now = _timing.CurTime;
        var sensorMode = FighterOptics.Mode(aircraft, now);
        eye.DrawLight = sensorMode == FighterSensorMode.Normal;
        // The aircraft is drawn nose-up. Use its interpolated heading for the
        // exterior so terrain always travels toward the tail, including southbound
        // runs. The independent reconnaissance camera remains north-up.
        eye.Rotation = Angle.Zero;
        exteriorEye.Rotation = exteriorHeading;
        // Eye zoom is local state too; server PVS sizing does not set client zoom.
        eye.Zoom = new Vector2((1.2f + aircraft.Height / 1000f) * (seat.Zoomed ? .5f : 1f));
        exteriorEye.Zoom = new Vector2(2f + aircraft.Height / 1000f);

        var point = FighterFlight.SensorPosition(aircraft, seat);
        var available = FighterFlight.SensorAvailable(aircraft, point, seat);
        Handoff.SetFlight(aircraft, now);
        // Use the interpolated exterior eye for both terrain and cloud motion.
        // The independent sensor point may remain locked while the jet flies past.
        var outsidePoint = exteriorEye.Position.Position;
        var outsideAvailable = FighterFlight.ExteriorAvailable(aircraft, outsidePoint);
        Ground.Visible = _airspace && available;
        Exterior.Visible = _airspace && outsideAvailable;
        _clouds.SetFlight(aircraft, point, available);
        _exteriorClouds.SetFlight(aircraft, outsidePoint, outsideAvailable);
        _chart.SetFlight(aircraft, chart, seat.Pilot && !_spectating);
        _chart.SetWeapons(weapons, seat, combat, now);
        _chart.SetEffects(effects);
        Ship.Visible = Effects.Visible = _airspace;
        Ship.SetAircraft(aircraft, pilotCrew, observerCrew);
        Effects.SetFlight(Ship, aircraft, weapons, combat, effects);
        _sight.SetFlight(aircraft, seat, weapons, available, now);
        // Animation stays smooth; text and target reconciliation follow network state.
        if (now < _nextReadouts) return;
        _nextReadouts = now + TimeSpan.FromMilliseconds(100);
        UpdateWeapons(aircraft, weapons, seat, now);
        Swap.Disabled = seat.Pilot ? observerCrew != null : pilotCrew != null;

        var obscured = !available || FighterOptics.CloudsBlock(aircraft, point, now);
        NormalVision.Lit = sensorMode == FighterSensorMode.Normal;
        NightVision.Lit = sensorMode == FighterSensorMode.NightVision;
        ThermalVision.Lit = sensorMode == FighterSensorMode.Thermal;
        ThermalVision.Disabled = !ThermalVision.Lit && !FighterOptics.ThermalReady(aircraft, now);
        var remaining = ThermalVision.Lit ? aircraft.ThermalUntil - now : aircraft.ThermalReadyAt - now;
        var seconds = (int) Math.Ceiling(Math.Max(0, remaining.TotalSeconds));
        ThermalStatus.Visible = ThermalVision.Lit || seconds > 0;
        ThermalStatus.Text = Loc.GetString(ThermalVision.Lit ? "cmu-fighter-thermal-active"
            : seconds > 0 ? "cmu-fighter-thermal-cooling" : "cmu-fighter-thermal-ready", ("time", $"{seconds / 60}:{seconds % 60:00}"));
        ThermalStatus.Warning = ThermalVision.Lit ? seconds <= 15 : seconds > 0;
        var phase = Loc.GetString(aircraft.GroundState == FighterGroundState.Airborne
            ? "cmu-fighter-console-phase-" + aircraft.Phase.ToString().ToLowerInvariant()
            : "cmu-fighter-ground-" + aircraft.GroundState.ToString().ToLowerInvariant());
        FlightDisplay.Text = groundScene ? phase : Loc.GetString("cmu-fighter-console-flight",
            ("phase", phase), ("height", MathF.Round(aircraft.Height)), ("speed", MathF.Round(aircraft.Speed)));
        FlightDisplay.Emphasis = 0;
        if (effects != null)
            foreach (var cue in effects.Cues)
                if (cue.Kind is FighterEffectKind.Launch or FighterEffectKind.Pass or FighterEffectKind.Return or FighterEffectKind.Holding or FighterEffectKind.Repaired &&
                    FighterEffects.Active(effects, cue, now))
                    FlightDisplay.Emphasis = Math.Max(FlightDisplay.Emphasis, MathF.Exp(-FighterEffects.Age(effects, cue, now) * 2));

        var locked = seat.SensorLock != null;
        var inRange = FighterFlight.SensorInRange(aircraft, point, seat);
        SensorStatus.Text = Loc.GetString("cmu-fighter-sensor-status",
            ("mode", Loc.GetString(!inRange ? "cmu-fighter-sensor-out-of-range" : locked ? "cmu-fighter-sensor-locked" : "cmu-fighter-sensor-following")),
            ("distance", MathF.Round(Vector2.Distance(aircraft.Position, point))),
            ("range", MathF.Round(seat.Target != null ? FighterFlight.DesignationRange(aircraft) : FighterFlight.SensorRange(aircraft))));
        SensorStatus.Warning = !inRange;
        Feed.Text = Loc.GetString(!inRange ? "cmu-fighter-sensor-out-of-range"
            : !available ? "cmu-fighter-standby" : obscured ? "cmu-fighter-obscured" : "cmu-fighter-clear");
        Feed.Warning = obscured;
        var incoming = weapons?.Targets.Any(target => target.Id == seat.Target && target.Incoming && now < target.ExpiresAt) == true;
        Observation.Text = Loc.GetString(incoming ? "cmu-fighter-missile-incoming" : weapons?.Targets.Count > 0 ? "cmu-fighter-targets-help" : "cmu-fighter-targets-empty");
        Observation.Warning = incoming;
        Launch.Disabled = !seat.Pilot || aircraft.Flying || aircraft.ForcedRetreat || _chart.HasDraft ||
            aircraft.GroundState != FighterGroundState.Airborne;
        Return.Text = Loc.GetString(_grounded ? "cmu-fighter-takeoff" : aircraft.GroundEntity != null ? "cmu-fighter-land" : "cmu-fighter-return");
        Return.Disabled = !seat.Pilot || aircraft.ForcedRetreat || (!_grounded && (aircraft.GroundEntity != null
            ? aircraft.GroundState != FighterGroundState.Airborne : aircraft.Phase is not (FighterPhase.Approach or FighterPhase.Pass)));
        Return.StatusColor = Color.FromHex("#8FCAAF");
        Leave.Text = Loc.GetString(_grounded ? "cmu-fighter-unbuckle" : "cmu-fighter-eject");
        Leave.StatusColor = _grounded ? null : Color.FromHex("#E98065");
        EjectPanel.Visible = !_grounded && seat.EjectConfirmUntil > now;
        EjectWarning.Text = Loc.GetString(seat.Pilot ? "cmu-fighter-eject-both-warning" : "cmu-fighter-eject-self-warning");
        Entry.Disabled = Exit.Disabled = !seat.Pilot || aircraft.Flying;
        Entry.Lit = _chart.EditEntry;
        Exit.Lit = !_chart.EditEntry;
        Apply.Disabled = !seat.Pilot || aircraft.Flying || !_chart.HasDraft;
        Mark.Disabled = !_airspace || obscured;
        Laser.Disabled = !_airspace || aircraft.ForcedRetreat || obscured && seat.Laser == null;
        Laser.Lit = seat.Laser != null;
        CameraLock.Disabled = !locked && !available;
        CameraLock.Lit = locked;
        CameraLock.Text = Loc.GetString(locked ? "cmu-fighter-unlock" : "cmu-fighter-lock");
        CameraZoom.Lit = seat.Zoomed;
        RouteStatus.Text = Loc.GetString(aircraft.Flying ? "cmu-fighter-route-locked"
            : !seat.Pilot ? "cmu-fighter-officer-route-hint" : _chart.EditEntry ? "cmu-fighter-pick-entry" : "cmu-fighter-pick-exit");
        FlightHelp.Text = Loc.GetString(_grounded ? seat.Pilot ? "cmu-fighter-taxi-help" : "cmu-fighter-ground-officer-help"
            : groundScene ? "cmu-fighter-vtol-help" : CameraControl ? "cmu-fighter-targeting-keys"
            : seat.Pilot ? "cmu-fighter-console-flight-help" : "cmu-fighter-officer-route-hint");
        UpdateAirCombat(aircraft, weapons, seat, combat, now);
        UpdatePresets(aircraft, seat.Pilot);
        if (_spectating)
        {
            FlightSettings.Visible = MissionActions.Visible = Swap.Visible = EjectPanel.Visible = false;
            RunAssist.Visible = FireControls.Visible = IncomingFlares.Visible = false;
            FlightHelp.Text = Loc.GetString(StopObserving.Visible
                ? "cmu-fighter-spectating-exit-help" : "cmu-fighter-spectating-help");
            RouteStatus.Text = Loc.GetString("cmu-fighter-spectating-help");
            DisableCrewControls(this);
        }
    }

    private void DisableCrewControls(Control control)
    {
        // Spectators can change their own display and stop following the crew.
        if (control is BaseButton button && button != FlightTab && button != TargetingTab && button != AirCover &&
            button != StopObserving)
            button.Disabled = true;
        foreach (var child in control.Children) DisableCrewControls(child);
    }

    private void UpdateWeapons(FighterAircraftComponent aircraft, FighterWeaponsComponent? weapons, FighterSeatComponent seat, TimeSpan now)
    {
        if (weapons == null) { Fire.Disabled = true; return; }
        var weapon = weapons.Loadout.FirstOrDefault(slot => slot.Slot == seat.WeaponSlot);
        var flare = weapons.Targets.FirstOrDefault(target => target.Id == seat.Target);
        foreach (var slot in weapons.Loadout)
        {
            if (slot.Slot < 0 || slot.Slot >= _weapons.Count) continue;
            var button = _weapons[slot.Slot];
            button.Text = slot.Slot == FighterWeaponsComponent.GauSlot ? Loc.GetString("cmu-fighter-kind-gau") :
                Loc.GetString("cmu-fighter-slot", ("number", slot.Slot + 1),
                    ("kind", Loc.GetString("cmu-fighter-kind-" + slot.Kind.ToString().ToLowerInvariant())));
            button.Lit = slot.Slot == seat.WeaponSlot;
            button.Disabled = !seat.Pilot && slot.Kind is FighterWeaponKind.Gau or FighterWeaponKind.Rockets;
            button.ToolTip = button.Disabled ? Loc.GetString("cmu-fighter-fire-pilotonly") : slot.Name;
        }
        var status = FighterWeapons.Status(aircraft, weapons, seat, weapon, flare, now);
        var strafing = seat.Pilot && weapon?.Kind is FighterWeaponKind.Gau or FighterWeaponKind.Rockets;
        RunAssist.Visible = strafing && _airspace;
        PrepareRun.Disabled = aircraft.Flying || aircraft.ForcedRetreat || flare is not { Laser: false, CanStrike: true };
        QueueFire.Disabled = !seat.FireQueued && !FighterRunAssist.CanQueue(aircraft, seat, weapon, flare);
        QueueFire.Lit = seat.FireQueued;
        QueueFire.Text = Loc.GetString(seat.FireQueued ? "cmu-fighter-cancel-queue" : "cmu-fighter-queue-fire");
        WeaponName.Text = weapon == null ? Loc.GetString("cmu-fighter-empty-pylon") :
            Loc.GetString("cmu-fighter-weapon-brief", ("name", weapon.Name), ("rounds", weapon.Rounds));
        WeaponName.ToolTip = weapon == null ? null : Loc.GetString("cmu-fighter-weapon-status", ("name", weapon.Name),
            ("rounds", weapon.Rounds), ("target", flare?.Name ?? "—"));
        FireStatus.Text = status == FighterFireStatus.Locking
            ? Loc.GetString("cmu-fighter-lock-countdown", ("seconds", Math.Max(0, (seat.LaserLockReadyAt - now).TotalSeconds).ToString("0.0")))
            : Loc.GetString("cmu-fighter-fire-" + status.ToString().ToLowerInvariant());
        if (strafing && flare != null)
            FireStatus.Text = Loc.GetString("cmu-fighter-run-range", ("status", FireStatus.Text),
                ("distance", MathF.Round(Vector2.Distance(aircraft.Position, flare.Position))), ("range", weapons.RunRange));
        FireStatus.Warning = status != FighterFireStatus.Ready;
        Fire.Disabled = status != FighterFireStatus.Ready;
        Fire.Lit = !Fire.Disabled;
        Fire.Text = Loc.GetString(flare is { Laser: true } ? "cmu-fighter-lock-fire" : "cmu-fighter-fire-button");
        foreach (var id in _targets.Keys.Where(id => weapons.Targets.All(target => target.Id != id)).ToArray())
        {
            _targets[id].Orphan();
            _targets[id].Dispose();
            _targets.Remove(id);
        }
        foreach (var target in weapons.Targets)
        {
            if (!_targets.TryGetValue(target.Id, out var button))
            {
                button = new FighterCockpitButton { MinHeight = 28, MaxHeight = 32 };
                var id = target.Id;
                button.OnPressed += _ => { _selectTarget(id); ShowOptics(true); };
                TargetList.AddChild(button);
                _targets.Add(id, button);
            }
            var targetStatus = FighterWeapons.Status(aircraft, weapons, seat, weapon, target, now);
            var name = target.Laser ? Loc.GetString("cmu-fighter-laser-time", ("name", target.Name),
                ("seconds", (int) Math.Ceiling(Math.Max(0, (target.ExpiresAt - now).TotalSeconds)))) : target.Name;
            button.Text = name;
            button.ToolTip = Loc.GetString("cmu-fighter-fire-" + targetStatus.ToString().ToLowerInvariant());
            button.Lit = seat.Target == target.Id;
            button.StatusColor = targetStatus == FighterFireStatus.Ready ? Color.LimeGreen : Color.Orange;
        }
    }
}
