- type: job
  parent: CMJobBase
  id: RuMCUPPLiquidatorMedic
  roundSide: ThirdParty
  roundForce: UPP
  roundRole: RuMCUPPLiquidatorMedic
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_pvt
  - type: AssignSquad
    whitelist:
      tags:
      - RuMCSquadLiquidator
  - type: Skills
    skills:
      RMCSkillEngineer: 2
      RMCSkillConstruction: 1
      RMCSkillFirearms: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillPolice: 1
      RMCSkillFireman: 3
      RMCSkillVehicles: 2
      RMCSkillJtac: 1
      RMCSkillMedical: 2
      RMCSkillSurgery: 3
  - type: JobPrefix
    prefix: rumc-job-prefix-rifleman
  - type: MarineOrders
  - type: RMCTrackable
  - type: RMCPointing
  - type: Language
    spokenLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    understoodLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    currentLanguage: Russian
    defaultLanguage: Russian

  name: Medic
  description: Liquidator Medic
  playTimeTracker: RuMCJobUPPLiquidatorMedic
  ranks:
    RMCRankCivilian: []
  chevrons:
    UPP_Private:
      entity: AU14ChevronUPPNIPrivate
      requirements: []
    UPP_Gefreiter:
      entity: AU14ChevronUPPNIGefreiter
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPLiquidatorMedic
        time: 1800 # 0.5 hours
    UPP_SeniorGefreiter:
      entity: AU14ChevronUPPNISeniorGefreiter
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPLiquidatorMedic
        time: 5400 # 1.5 hours
  spawnMenuRoleName: Liquidator Medic
  startingGear: RuMCGearUPPLiquidatorMedic
  greeting: rumc-liquidator-greeting
  icon: "RuMCJobIconUPPLiquidatorMedic"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: RuMCBaseMobSpeciesOrganicUPPBEAR
  id: RuMCJobUPPLiquidatorMedic
  name: Liquidator Medic
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: RuMCSquadLiquidator
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Liquidator Medic
    description: Вы член группы ликвидаторов UPP! Ваша задача выжечь дотла всю биологическую угрозу на колонии, ни шагу назад!
    job: RuMCUPPLiquidatorMedic
    raffle:
      settings: short

- type: startingGear
  parent: RuMCGearUPPBEARbase
  id: RuMCGearUPPLiquidatorMedic
  equipment:
    id: RuCMIDCardUPPLiquidatorMedic
    outerClothing: RMCOuterClothingExternalWebbingBrownFull
    jumpsuit: CMJumpsuitSPPEngi
    shoes: RMCBootsSPPFilled
    head: RMCHardhatOrange
    belt: AU14BeltMedicBagProdigyFilled
    pocket1: AU14PouchIFAKFill
    pocket2: AU14PouchIFAKFill
    back: RMCSatchelSPPFullMarksman
    ears: RuMCHeadsetLiquidator
    suitstorage: RMCWeaponRifleAK4047
  inhand:
    - AU14CBRNKitUPP

- type: jobIcon
  parent: CMJobIconBase
  id: RuMCJobIconUPPLiquidatorMedic
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: upp_pvt

- type: playTimeTracker
  id: RuMCJobUPPLiquidatorMedic
