- type: loadoutGroup
  id: AU14ColonistSkillGroupConstruction
  name: loadout-group-au14-colonist-skill-construction
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillConstruction1, AU14ColonistSkillConstruction2, AU14ColonistSkillConstruction3 ]
- type: loadout
  id: AU14ColonistSkillConstruction1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillConstruction, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillConstruction2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillConstruction, level: 2 } ]
- type: loadout
  id: AU14ColonistSkillConstruction3
  cost: 9
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillConstruction, level: 3 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupCqc
  name: loadout-group-au14-colonist-skill-cqc
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillCqc1, AU14ColonistSkillCqc2 ]
- type: loadout
  id: AU14ColonistSkillCqc1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillCqc, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillCqc2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillCqc, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupDomestics
  name: loadout-group-au14-colonist-skill-domestics
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillDomestics1, AU14ColonistSkillDomestics2 ]
- type: loadout
  id: AU14ColonistSkillDomestics1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillDomestics, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillDomestics2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillDomestics, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupEndurance
  name: loadout-group-au14-colonist-skill-endurance
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillEndurance1, AU14ColonistSkillEndurance2 ]
- type: loadout
  id: AU14ColonistSkillEndurance1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillEndurance, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillEndurance2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillEndurance, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupEngineer
  name: loadout-group-au14-colonist-skill-engineer
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillEngineer1, AU14ColonistSkillEngineer2, AU14ColonistSkillEngineer3 ]
- type: loadout
  id: AU14ColonistSkillEngineer1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillEngineer, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillEngineer2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillEngineer, level: 2 } ]
- type: loadout
  id: AU14ColonistSkillEngineer3
  cost: 9
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillEngineer, level: 3 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupFirearms
  name: loadout-group-au14-colonist-skill-firearms
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillFirearms1, AU14ColonistSkillFirearms2, AU14ColonistSkillFirearms3 ]
- type: loadout
  id: AU14ColonistSkillFirearms1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillFirearms, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillFirearms2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillFirearms, level: 2 } ]
- type: loadout
  id: AU14ColonistSkillFirearms3
  cost: 9
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillFirearms, level: 3 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupFireman
  name: loadout-group-au14-colonist-skill-fireman
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillFireman1, AU14ColonistSkillFireman2 ]
- type: loadout
  id: AU14ColonistSkillFireman1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillFireman, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillFireman2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillFireman, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupIntel
  name: loadout-group-au14-colonist-skill-intel
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillIntel1, AU14ColonistSkillIntel2 ]
- type: loadout
  id: AU14ColonistSkillIntel1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillIntel, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillIntel2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillIntel, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupJtac
  name: loadout-group-au14-colonist-skill-jtac
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillJtac1, AU14ColonistSkillJtac2 ]
- type: loadout
  id: AU14ColonistSkillJtac1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillJtac, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillJtac2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillJtac, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupLeadership
  name: loadout-group-au14-colonist-skill-leadership
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillLeadership1, AU14ColonistSkillLeadership2 ]
- type: loadout
  id: AU14ColonistSkillLeadership1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillLeadership, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillLeadership2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillLeadership, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupMedical
  name: loadout-group-au14-colonist-skill-medical
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillMedical1, AU14ColonistSkillMedical2, AU14ColonistSkillMedical3 ]
- type: loadout
  id: AU14ColonistSkillMedical1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillMedical, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillMedical2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillMedical, level: 2 } ]
- type: loadout
  id: AU14ColonistSkillMedical3
  cost: 9
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillMedical, level: 3 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupMeleeWeapons
  name: loadout-group-au14-colonist-skill-melee-weapons
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillMeleeWeapons1, AU14ColonistSkillMeleeWeapons2 ]
- type: loadout
  id: AU14ColonistSkillMeleeWeapons1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillMeleeWeapons, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillMeleeWeapons2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillMeleeWeapons, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupNavigations
  name: loadout-group-au14-colonist-skill-navigations
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillNavigations1, AU14ColonistSkillNavigations2 ]
- type: loadout
  id: AU14ColonistSkillNavigations1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillNavigations, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillNavigations2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillNavigations, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupOverwatch
  name: loadout-group-au14-colonist-skill-overwatch
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillOverwatch1, AU14ColonistSkillOverwatch2 ]
- type: loadout
  id: AU14ColonistSkillOverwatch1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillOverwatch, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillOverwatch2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillOverwatch, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupPilot
  name: loadout-group-au14-colonist-skill-pilot
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillPilot1, AU14ColonistSkillPilot2 ]
- type: loadout
  id: AU14ColonistSkillPilot1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPilot, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillPilot2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPilot, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupPolice
  name: loadout-group-au14-colonist-skill-police
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillPolice1, AU14ColonistSkillPolice2 ]
- type: loadout
  id: AU14ColonistSkillPolice1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPolice, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillPolice2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPolice, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupPowerLoader
  name: loadout-group-au14-colonist-skill-power-loader
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillPowerLoader1, AU14ColonistSkillPowerLoader2 ]
- type: loadout
  id: AU14ColonistSkillPowerLoader1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPowerLoader, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillPowerLoader2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillPowerLoader, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupResearch
  name: loadout-group-au14-colonist-skill-research
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillResearch1, AU14ColonistSkillResearch2 ]
- type: loadout
  id: AU14ColonistSkillResearch1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillResearch, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillResearch2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillResearch, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupSurgery
  name: loadout-group-au14-colonist-skill-surgery
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillSurgery1, AU14ColonistSkillSurgery2, AU14ColonistSkillSurgery3 ]
- type: loadout
  id: AU14ColonistSkillSurgery1
  cost: 2
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillSurgery, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillSurgery2
  cost: 5
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillSurgery, level: 2 } ]
- type: loadout
  id: AU14ColonistSkillSurgery3
  cost: 9
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillSurgery, level: 3 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupVehicles
  name: loadout-group-au14-colonist-skill-vehicles
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: [ AU14ColonistSkillVehicles1, AU14ColonistSkillVehicles2 ]
- type: loadout
  id: AU14ColonistSkillVehicles1
  cost: 1
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillVehicles, level: 1 } ]
- type: loadout
  id: AU14ColonistSkillVehicles2
  cost: 3
  effects: [ !type:SetSkillLoadoutEffect { skill: RMCSkillVehicles, level: 2 } ]

- type: loadoutGroup
  id: AU14ColonistSkillGroupSpecial
  name: loadout-group-au14-colonist-skill-special
  hidden: true
  minLimit: 0
  maxLimit: 3
  loadouts: []

- type: loadoutGroup
  id: AU14ColonistSkillGroupGear
  name: loadout-group-au14-colonist-skill-gear
  hidden: true
  minLimit: 0
  maxLimit: 1
  loadouts: []

- type: roleLoadout
  id: AU14ColonistSpecialLoadout
  points: 20
  groups:
  - AU14ColonistSpecialLoadoutGroup
  - AU14ColonistSpecialGroupCqc
  - AU14ColonistSpecialGroupMelee
  - AU14ColonistSpecialGroupMedical
  - AU14ColonistSpecialGroupSurgery
  - AU14ColonistSpecialGroupMedSurgery
  - AU14ColonistSpecialGroupEngineer
  - AU14ColonistSpecialGroupConstruction
  - AU14ColonistSpecialGroupEngConstruction
  - AU14ColonistSpecialGroupFirearmsEngineer
  - AU14ColonistSpecialGroupResearch
  - AU14ColonistSpecialGroupLeadership
  - AU14ColonistSpecialGroupJtac
  - AU14ColonistSpecialGroupDomestics
  - AU14ColonistSpecialGroupEndurance
  - AU14ColonistSpecialGroupEnduranceMelee
  - AU14ColonistSpecialGroupVehicles
  - AU14ColonistClothingGroup

- type: loadoutGroup
  id: AU14ColonistSpecialLoadoutGroup
  name: loadout-group-au14-colonist-special-loadout
  hidden: true
  minLimit: 0
  maxLimit: 20
  loadouts: [ AU14ColonistLoadoutD18Case, AU14ColonistLoadoutM357Kit, AU14ColonistLoadoutBasiraRifle, AU14ColonistLoadoutGlock77Rubber, AU14ColonistLoadoutM50Hazops, AU14ColonistLoadoutRXFM, AU14ColonistLoadoutT73, AU14ColonistLoadoutZHNK72 ]
