using System.Linq;
// cmu edit start
using Content.Shared.Humanoid;
// cmu edit end
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;

    // cmu edit start
    private HashSet<HumanoidVisualLayers> _ignoreLayers = new();

    public string IgnoreLayers
    {
        get => string.Join(',', _ignoreLayers);
        set
        {
            _ignoreLayers = value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(Enum.Parse<HumanoidVisualLayers>)
                .ToHashSet();
            UpdateMarkings();
        }
    }
    // cmu edit end

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganTabs.RemoveAllChildren();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            // cmu edit start
            var layers = organData.Layers.Where(layer => !_ignoreLayers.Contains(layer)).ToHashSet();
            var control = new OrganMarkingPicker(_markingsModel, organ, layers, organData.Group);
            // cmu edit end
            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = i > 1;
    }
}
