- type: job
  parent: CMJobBase
  id: RuMCUPPBEARRifleman
  roundSide: ThirdParty
  roundForce: BEAR
  roundRole: RuMCUPPBEARRifleman
  roundComponents:
  - type: TacticalMapIcon
    icon:
      sprite: /Textures/_RMC14/Interface/map_blips.rsi
      state: spp_pvt
  - type: AssignSquad
    whitelist:
      tags:
      - RuMCSquadBEAR
  - type: Skills
    skills:
      RMCSkillCqc: 1
      RMCSkillEngineer: 1
      RMCSkillConstruction: 1
      RMCSkillFirearms: 2
      RMCSkillMedical: 1
      RMCSkillMeleeWeapons: 1
      RMCSkillPolice: 2
      RMCSkillFireman: 3
      RMCSkillVehicles: 2
      RMCSkillJtac: 1
      RMCSkillEndurance: 2
  - type: EquipEntityPreset
    preset: RuMCBEARPreset
  - type: JobPrefix
    prefix: rumc-job-prefix-rifleman
  - type: MarineOrders
  - type: RMCTrackable
  - type: RMCPointing
  - type: Language
    spokenLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    understoodLanguages:
    - Polish
    - English
    - Russian
    - Spanish
    - Mandarin
    - German
    - TacticalSignLanguage
    currentLanguage: Russian
    defaultLanguage: Russian

  name: Rifleman
  description: CHTORM Rifleman
  playTimeTracker: RuMCJobUPPBEARRifleman
  ranks:
    RMCRankCivilian: []
  chevrons:
    UPP_Private:
      entity: AU14ChevronUPPNIPrivate
      requirements: []
    UPP_Gefreiter:
      entity: AU14ChevronUPPNIGefreiter
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPBEARRifleman
        time: 1800 # 0.5 hours
    UPP_SeniorGefreiter:
      entity: AU14ChevronUPPNISeniorGefreiter
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPBEARRifleman
        time: 5400 # 1.5 hours
    UPP_Corporal:
      entity: AU14ChevronUPPNICorporal
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPBEARRifleman
        time: 7200 # 2 hours
    UPP_Plutonowy:
      entity: AU14ChevronUPPNIPlutonowy
      requirements:
      - !type:RoleTimeRequirement
        role: RuMCJobUPPBEARRifleman
        time: 10800 # 3 hours
  spawnMenuRoleName: CHTORM Rifleman
  startingGear: RuMCGearUPPBEARRifleman
  greeting: rumc-bear-greeting
  icon: "RuMCJobIconUPPBEARRifleman"
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: RuMCBaseMobSpeciesOrganicUPPBEAR
  id: RuMCJobUPPBEARRifleman
  name: CHTORM Rifleman
  components:
  - type: EquipEntityPreset
    preset: RuMCBEARPreset
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: RuMCSquadBEAR
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: CHTORM Rifleman
    description: The primary combat unit of the BEAR PMC. Armed with the AK-13 assault carbine. A versatile fighter for any mission — from reconnaissance to assault. Fast, accurate, reliable.
    job: RuMCUPPBEARRifleman
    raffle:
      settings: short

- type: startingGear
  parent: RuMCGearUPPBEARbase
  id: RuMCGearUPPBEARRifleman
  equipment:
    id: RuCMIDCardUPPBEARRifleman
    ears: RuMCHeadsetBEAR
  storage:
    back:
    - RMCMRESPP
    - AU14PacketGrenadeHighExplosiveUPPFilled
    - AU14GrenadeSmokeUPP
    - RMCExplosiveBreachingCharge

- type: jobIcon
  parent: CMJobIconBase
  id: RuMCJobIconUPPBEARRifleman
  icon:
    sprite: _RMC14/Interface/cm_job_icons.rsi
    state: upp_pvt

- type: playTimeTracker
  id: RuMCJobUPPBEARRifleman
