using Content.Shared.CMU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class DepartmentConsoleWindow : DefaultWindow
{
    public event Action<NetEntity>? OnFirePressed;
    public event Action<NetEntity, int>? OnSetIndividualSalaryPressed;
    public event Action<NetEntity>? OnRemoveOverridePressed;
    public event Action<int, int, string, string>? OnOrderPressed;

    public DepartmentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        TabContainer.SetTabTitle(ManagementTab, Loc.GetString("department-console-management-tab"));
        TabContainer.SetTabTitle(OrdersTab, Loc.GetString("department-console-orders-tab"));
    }

    public void UpdateState(DepartmentConsoleBuiState state)
    {
        DeptNameLabel.Text = state.DepartmentName;
        DeptBudgetLabel.Text = Loc.GetString("department-console-department-budget", ("amount", state.DepartmentBudget.ToString("F0")));
        OrdersBudgetLabel.Text = Loc.GetString("department-console-department-budget", ("amount", state.DepartmentBudget.ToString("F0")));
        DefaultSalaryInput.Text = state.DefaultSalary.ToString();

        // Rebuild employee list
        EmployeeList.RemoveAllChildren();

        foreach (var emp in state.Employees)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };

            var nameLabel = new Label
            {
                Text = emp.Name,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 2
            };

            var jobLabel = new Label
            {
                Text = emp.JobTitle,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var salaryLabel = new Label
            {
                Text = Loc.GetString(emp.HasOverride
                        ? "department-console-salary-custom"
                        : "department-console-salary",
                    ("amount", emp.Salary)),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var salaryInput = new LineEdit
            {
                PlaceHolder = Loc.GetString("department-console-salary-placeholder"),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var setSalaryBtn = new Button { Text = Loc.GetString("department-console-set") };
            var idCopy = emp.IdCardUid;
            setSalaryBtn.OnPressed += _ =>
            {
                if (salaryInput.Text is { } text && int.TryParse(text, out var salary))
                    OnSetIndividualSalaryPressed?.Invoke(idCopy, salary);
            };

            var resetBtn = new Button { Text = Loc.GetString("department-console-reset") };
            resetBtn.OnPressed += _ => OnRemoveOverridePressed?.Invoke(idCopy);

            var fireBtn = new Button { Text = Loc.GetString("department-console-fire") };
            fireBtn.OnPressed += _ => OnFirePressed?.Invoke(idCopy);

            row.AddChild(nameLabel);
            row.AddChild(jobLabel);
            row.AddChild(salaryLabel);
            row.AddChild(salaryInput);
            row.AddChild(setSalaryBtn);
            row.AddChild(resetBtn);
            row.AddChild(fireBtn);

            EmployeeList.AddChild(row);
        }

        if (state.Employees.Count == 0)
        {
            EmployeeList.AddChild(new Label { Text = Loc.GetString("department-console-no-employees") });
        }

        // Rebuild order catalog categories
        OrderCategoryList.RemoveAllChildren();
        OrderItemList.RemoveAllChildren();
        SelectedCategoryLabel.Text = Loc.GetString("department-console-select-category");

        for (var catIdx = 0; catIdx < state.Catalog.Count; catIdx++)
        {
            var cat = state.Catalog[catIdx];
            var catBtn = new Button { Text = cat.Name };
            var catCopy = cat;
            catBtn.OnPressed += _ => ShowCategory(catCopy);
            OrderCategoryList.AddChild(catBtn);
        }

        if (state.Catalog.Count == 0)
        {
            OrderCategoryList.AddChild(new Label { Text = Loc.GetString("department-console-no-catalog") });
        }
    }

    private void ShowCategory(DepartmentOrderCatalogCategory category)
    {
        OrderItemList.RemoveAllChildren();
        SelectedCategoryLabel.Text = Loc.GetString("department-console-category", ("category", category.Name));

        foreach (var entry in category.Entries)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };

            var nameLabel = new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 3
            };

            var costLabel = new Label
            {
                Text = Loc.GetString("department-console-item-cost", ("amount", entry.Cost)),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var orderBtn = new Button { Text = Loc.GetString("department-console-order") };
            var catIdx = entry.CategoryIndex;
            var entIdx = entry.EntryIndex;
            orderBtn.OnPressed += _ =>
            {
                var reason = OrderReasonInput.Text ?? "";
                var deliverTo = OrderDeliverToInput.Text ?? "";
                OnOrderPressed?.Invoke(catIdx, entIdx, reason, deliverTo);
            };

            row.AddChild(nameLabel);
            row.AddChild(costLabel);
            row.AddChild(orderBtn);

            OrderItemList.AddChild(row);
        }

        if (category.Entries.Count == 0)
        {
            OrderItemList.AddChild(new Label { Text = Loc.GetString("department-console-no-items") });
        }
    }
}
