// cmu edit start: rebuilt as a CRT forensic report with death, injury, match and evidence cards
using System.Linq;
using Content.Client.Lobby.UI;
using Content.Shared.CMU14.Forensics;
using Content.Shared.Forensics.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Forensics;

[GenerateTypedNameReferences]
public sealed partial class ForensicScannerMenu : DefaultWindow
{
    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private IClipboardManager _clipboard = default!;

    private static readonly Color DeathColor = Color.FromHex("#E05A4F");
    private static readonly Color MatchColor = Color.FromHex("#E0C050");

    private TimeSpan? _printReady;

    public ForensicScannerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (string.IsNullOrEmpty(NameLabel.Text))
            return;

        Print.Disabled = _printReady > _gameTiming.CurTime;
    }

    public void Update(ForensicScannerComponent scanner)
    {
        Entries.RemoveAllChildren();

        if (string.IsNullOrEmpty(scanner.LastScannedName))
        {
            Print.Disabled = true;
            Clear.Disabled = true;
            NameLabel.Text = string.Empty;
            HeaderPanel.Visible = false;
            Diagnostics.Visible = true;
            return;
        }

        _printReady = scanner.PrintReadyAt;
        Clear.Disabled = false;
        NameLabel.Text = scanner.LastScannedName;
        HeaderPanel.Visible = true;
        Diagnostics.Visible = false;

        AddDeathCard(scanner);
        AddMatchCard(scanner);
        AddEvidenceCard(scanner);
        AddInjuryCard(scanner);

        CrtLobbyTheme.Apply(Entries);
    }

    private void AddDeathCard(ForensicScannerComponent scanner)
    {
        if (string.IsNullOrEmpty(scanner.CMUTimeSinceDeath) && string.IsNullOrEmpty(scanner.CMUCauseOfDeath))
            return;

        var body = AddCard("cmu-forensic-scanner-card-death");
        if (!string.IsNullOrEmpty(scanner.CMUCauseOfDeath))
            body.AddChild(KeyValue("cmu-forensic-scanner-cause-of-death", scanner.CMUCauseOfDeath, DeathColor));
        if (!string.IsNullOrEmpty(scanner.CMUTimeSinceDeath))
            body.AddChild(KeyValue("cmu-forensic-scanner-time-since-death", scanner.CMUTimeSinceDeath, null));
    }

    private void AddInjuryCard(ForensicScannerComponent scanner)
    {
        if (scanner.CMUInjuries.Count == 0)
            return;

        var body = AddCard("cmu-forensic-scanner-card-injuries");
        foreach (var group in scanner.CMUInjuries.GroupBy(i => i.Location))
        {
            body.AddChild(new Label
            {
                Text = group.Key,
                StyleClasses = { "CrtHeadingSmall" },
                Margin = new Thickness(0, 4, 0, 0),
            });

            foreach (var injury in group)
            {
                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 6,
                    Margin = new Thickness(8, 0, 0, 0),
                };
                row.AddChild(new Label
                {
                    Text = Loc.GetString($"cmu-forensic-scanner-severity-{injury.Severity.ToString().ToLowerInvariant()}"),
                    FontColorOverride = SeverityColor(injury.Severity),
                    MinWidth = 70,
                });
                row.AddChild(Wrapped(injury.Description));
                body.AddChild(row);
            }
        }
    }

    private void AddMatchCard(ForensicScannerComponent scanner)
    {
        if (scanner.Fingerprints.Count == 0 && scanner.DNAs.Count == 0)
            return;

        var body = AddCard("cmu-forensic-scanner-matches");
        if (scanner.CMURecordMatches.Count == 0)
        {
            body.AddChild(Dim("cmu-forensic-scanner-no-matches"));
            return;
        }

        foreach (var name in scanner.CMURecordMatches)
        {
            body.AddChild(new Label { Text = name, FontColorOverride = MatchColor });
        }
    }

    private void AddEvidenceCard(ForensicScannerComponent scanner)
    {
        var body = AddCard("cmu-forensic-scanner-card-evidence");
        AddEvidenceList(body, "forensic-scanner-interface-fingerprints", scanner.Fingerprints, true);
        AddEvidenceList(body, "forensic-scanner-interface-dnas", scanner.DNAs, true);
        AddEvidenceList(body, "forensic-scanner-interface-fibers", scanner.Fibers, false);
        AddEvidenceList(body, "forensic-scanner-interface-residues", scanner.Residues, false);
    }

    private void AddEvidenceList(BoxContainer body, string header, List<string> values, bool copyable)
    {
        body.AddChild(new Label
        {
            Text = Loc.GetString(header),
            StyleClasses = { "CrtHeadingSmall" },
            Margin = new Thickness(0, 4, 0, 0),
        });

        if (values.Count == 0)
        {
            var none = Dim("cmu-forensic-scanner-none");
            none.Margin = new Thickness(8, 0, 0, 0);
            body.AddChild(none);
            return;
        }

        foreach (var value in values)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 0, 0, 0),
            };
            var text = Wrapped(value);
            text.VerticalAlignment = VAlignment.Center;
            row.AddChild(text);

            if (copyable)
            {
                var copy = new Button
                {
                    Text = Loc.GetString("cmu-forensic-scanner-copy"),
                    ToolTip = Loc.GetString("cmu-forensic-scanner-copy-tooltip"),
                    Margin = new Thickness(4, 0, 0, 0),
                };
                var copied = value;
                copy.OnPressed += _ => _clipboard.SetText(copied);
                row.AddChild(copy);
            }

            body.AddChild(row);
        }
    }

    private BoxContainer AddCard(string title)
    {
        var card = new PanelContainer { StyleClasses = { "CrtInsetPanel" }, HorizontalExpand = true };
        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(6),
            SeparationOverride = 2,
        };

        var header = new PanelContainer { StyleClasses = { "CrtHeaderPanel" } };
        header.AddChild(new Label { Text = Loc.GetString(title), StyleClasses = { "CrtHeading" } });
        body.AddChild(header);

        card.AddChild(body);
        Entries.AddChild(card);
        return body;
    }

    private static BoxContainer KeyValue(string key, string value, Color? color)
    {
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
        row.AddChild(new Label { Text = Loc.GetString(key), StyleClasses = { "CrtDimText" } });
        row.AddChild(Wrapped(value, color));
        return row;
    }

    /// <summary>
    /// Text that wraps onto more lines instead of being cut off at the edge of the window.
    /// </summary>
    private static RichTextLabel Wrapped(string text, Color? color = null)
    {
        var message = new FormattedMessage();
        if (color != null)
            message.PushColor(color.Value);
        message.AddText(text);
        if (color != null)
            message.Pop();

        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMessage(message);
        return label;
    }

    private static Label Dim(string key)
    {
        return new Label { Text = Loc.GetString(key), StyleClasses = { "CrtDimText" } };
    }

    private static Color SeverityColor(CMUForensicInjurySeverity severity) => severity switch
    {
        CMUForensicInjurySeverity.Minor => Color.FromHex("#7FBF7F"),
        CMUForensicInjurySeverity.Moderate => Color.FromHex("#E0C050"),
        CMUForensicInjurySeverity.Severe => Color.FromHex("#E08A3C"),
        CMUForensicInjurySeverity.Critical => Color.FromHex("#E05A4F"),
        _ => Color.FromHex("#9A9A9A"),
    };
}
// cmu edit end
