using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CMU14.ForceOnForce;

[GenerateTypedNameReferences]
public sealed partial class ForceOnForceHijackJoinWindow : FancyWindow
{
    public ForceOnForceHijackJoinWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
