using Content.Shared.CCVar;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleRulesWindow : DefaultWindow
    {
        [Dependency] private IConfigurationManager _cfg = IoCManager.Resolve<IConfigurationManager>();
        [Dependency] private IStylesheetManager _stylesheetManager = default!;
        private readonly GhostRoleKind _ghostRoleKind;

        public GhostRoleRulesWindow(string rules, GhostRoleKind ghostRoleKind, Action<BaseButton.ButtonEventArgs> requestAction)
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
            ApplyCrtPalette();
            _ghostRoleKind = ghostRoleKind;

            TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(rules));
            RequestButton.Disabled = false;
            RequestButton.Text = GetButtonText();

            RequestButton.OnPressed += requestAction;
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
        }
        private string GetButtonText()
        {
            var messageId = _ghostRoleKind switch
            {
                GhostRoleKind.FirstComeFirstServe => "ghost-roles-window-request-role-button",
                GhostRoleKind.RaffleReady or GhostRoleKind.RaffleInProgress => "ghost-roles-window-join-raffle-button",
                GhostRoleKind.RaffleJoined => "ghost-roles-window-leave-raffle-button-confirm",
                _ => throw new ArgumentOutOfRangeException(nameof(_ghostRoleKind),
                    $"Unknown {nameof(GhostRoleKind)} '{_ghostRoleKind}'")
            };

            return Loc.GetString(messageId);
        }
    }
}
