using Content.Shared._RMC14.Overwatch;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.CMU14.TacticalMap.Reconstruction;

[GenerateTypedNameReferences]
public sealed partial class CMUReconCameraWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entities = default!;
    private readonly EntityUid _viewer;
    private readonly NetEntity _camera;

    public CMUReconCameraWindow(EntityUid viewer, NetEntity camera, string name)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _viewer = viewer;
        _camera = camera;
        Title = Loc.GetString("cmu-recon-camera-title", ("name", name));
        CameraViewport.ViewportSize = new Vector2i(640, 640);
        CameraViewport.RenderZLevels = true;
        CameraViewport.MinimumRenderInterval = TimeSpan.FromSeconds(1.0 / 30);
        CameraViewport.Eye = new FixedEye();
        Disconnect.OnPressed += _ => Close();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        // Use the existing overwatch eye and its server-managed PVS subscription.
        // A late network state must never display the operator's own eye as a helmet feed.
        var connected = _entities.TryGetComponent(_viewer, out OverwatchWatchingComponent? watching) &&
            watching.Watching is { } target && _entities.GetNetEntity(target) == _camera &&
            _entities.TryGetComponent(_viewer, out EyeComponent? eye) && eye.Target == target;
        CameraViewport.Visible = connected;
        if (connected && _entities.TryGetComponent(_viewer, out EyeComponent? currentEye))
            CameraViewport.Eye = currentEye.Eye;
    }
}
